name: Check Pipeline

on:
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test

        - name: Build app
        env:
          STATUS_REDIS_URL: "redis://localhost:6379"
          QUEUE_REDIS_URL: "redis://localhost:6379"
          EXCHANGE_HOST: "http://localhost:3000"
          NEXT_PUBLIC_WEBSOCKET_CONNECTION_STRING: "ws://localhost:3001"
        run: pnpm build